# Generated by Django 2.1.2 on 2018-10-17 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reserved', models.BooleanField(default=False)),
                ('abv', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tasting_notes', models.TextField()),
                ('notes', models.TextField()),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerfest.Bar')),
            ],
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserBeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starred', models.BooleanField(default=True)),
                ('tried', models.BooleanField(default=False)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerfest.Beer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerfest.Brewery'),
        ),
    ]
