# Generated by Django 2.1.2 on 2018-10-18 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beerfest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bar',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='beer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='brewery',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='userbeer',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='userbeer',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbeer', to='beerfest.Beer'),
        ),
        migrations.AlterField(
            model_name='userbeer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbeer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userbeer',
            unique_together={('user', 'beer')},
        ),
    ]
