# Generated by Django 2.1.2 on 2018-10-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerfest', '0002_auto_20181018_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='tasting_notes',
            field=models.TextField(blank=True),
        ),
    ]
